version: "3.4"

services:
  saleor:
    image: saleor
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    command: sleep infinity
    env_file:
      - common.env
      - backend.env
    depends_on:
      - db
      - redis
    volumes:
      - ..:/app
    # 👇 Exponer el puerto para acceso local y pipeline
    ports:
      - 8000:8000

  dashboard:
    image: ghcr.io/saleor/saleor-dashboard:3.20.5
    restart: unless-stopped
    ports:
      - 9000:80

  db:
    image: library/postgres:15-alpine
    ports:
     - 5432:5432
    restart: unless-stopped
    volumes:
      - saleor-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=saleor
      - POSTGRES_PASSWORD=saleor
      - POSTGRES_DB=saleor  # 👈 agregado por compatibilidad con el pipeline

  redis:
    image: library/redis:7.0-alpine
    restart: unless-stopped
    volumes:
      - saleor-redis:/data
    ports:
      - 6379:6379

  mailpit:
    image: axllent/mailpit
    ports:
      - 1025:1025 # SMTP Server
      - 8025:8025 # Mailpit UI
    restart: unless-stopped

  # 👇 Nuevo contenedor para gestionar visualmente la base de datos
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5050:80
    depends_on:
      - db

volumes:
  saleor-db:
    driver: local
  saleor-redis:
    driver: local
